name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: '4.6-stable'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  SCONS_CACHE_LIMIT: 7168
  BASE_BUILD_FLAGS: >
    disable_path_overrides=no
    optimize=speed
    production=yes
    lto=full
    use_static_cpp=yes
    openxr=no
  #safe to assume no one will miss vr modules on PM ;]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        type: [release, debug, mono_release, mono_debug]
        include:
          - arch: x86_64
            scons_arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            scons_arch: arm64
            runner: ubuntu-24.04-arm

          - type: release
            target: template_release
            middle: ""
            flags: ""
          - type: debug
            target: template_debug
            middle: "debug."
            flags: ""
          - type: mono_release
            target: template_release
            middle: "mono."
            flags: "module_mono_enabled=yes"
          - type: mono_debug
            target: template_debug
            middle: "mono.debug."
            flags: "module_mono_enabled=yes"
              
    runs-on: ${{ matrix.runner }}
    steps:
      - run: sudo apt-get update && sudo apt-get install -y squashfs-tools
      
      - uses: actions/checkout@v6
        with:
          path: builder_repo
        
      - uses: actions/checkout@v6
        with:
          repository: godotengine/godot
          ref: '${{ inputs.ref }}'
          path: godot_source

      - uses: actions/setup-dotnet@v5
        if: contains(matrix.type, 'mono')
        with:
          dotnet-version: 8.0.100
        
      - uses: actions/cache@v5
        with:
          path: godot_source/.scons-cache
          key: scons-${{ matrix.arch }}-${{ matrix.type }}-${{ inputs.ref }}-${{ github.run_id }}
          restore-keys: scons-${{ matrix.arch }}-${{ matrix.type }}-

      - run: |
          mkdir -p builder_repo/dotnet
          if [[ "${{ matrix.type }}" == mono_* ]]; then
            cp -R "$DOTNET_ROOT"/* builder_repo/dotnet/
          fi
          touch builder_repo/dotnet/.gitkeep
          
      - run: docker build --build-arg ARCH=${{ matrix.arch }} -f builder_repo/.github/Dockerfile -t local-builder builder_repo
      
      - run: |
          cd godot_source
          docker run --rm \
            -v "$PWD":/w \
            -w /w \
            -e HOME=/tmp \
            --user $(id -u):$(id -g) \
            local-builder \
            scons -j$(nproc) \
            cache_path=/w/.scons-cache \
            platform=linuxbsd \
            arch=${{ matrix.scons_arch }} \
            target=${{ matrix.target }} \
            ${BASE_BUILD_FLAGS} \
            ${{ matrix.flags }}
          
          cd bin
          VERSION="${{ inputs.ref }}"
          VERSION="${VERSION%-stable}"
          SHORTVER="${VERSION//./}"
          SUFFIX="${{ matrix.arch }}"
          [ "$SUFFIX" = "arm64" ] && SUFFIX="aarch64"
          
          BIN_NAME="godot${SHORTVER}.${{ matrix.middle }}${SUFFIX}"
          ORIG_BIN=$(ls godot.linuxbsd.${{ matrix.target }}.${{ matrix.scons_arch }}*)
          
          strip "$ORIG_BIN" \
            && mv "$ORIG_BIN" "$BIN_NAME" \
            && chmod 777 "$BIN_NAME"
          
          mksquashfs "$BIN_NAME" \
            "godot_${VERSION}.${{ matrix.middle }}${SUFFIX}.squashfs" \
            -noappend \
            -comp gzip \
            >/dev/null
          
          cat <<EOF > flags_${{ matrix.type }}_${{ matrix.arch }}.md
          ### SCons Flags: ${{ matrix.type }} (${{ matrix.arch }})
          \`\`\`bash
          platform=linuxbsd arch=${{ matrix.scons_arch }} target=${{ matrix.target }} ${BASE_BUILD_FLAGS} ${{ matrix.flags }}
          \`\`\`
          EOF
          
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.type }}-${{ matrix.arch }}
          path: |
            godot_source/bin/*.squashfs
            godot_source/bin/flags_*.md

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: release_assets
          merge-multiple: true
        
      - run: cat release_assets/flags_*.md > notes.md
      
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.ref }}
          body_path: notes.md
          files: release_assets/*.squashfs